### ISSUE TITLE
Gracefully Handle Rolling Weapons With Missing Data

### ISSUE THREAD

**Issue by cyface** [cyface/foundryvtt-dcc#12] opened 2020-07-19 13:48 UTC
If someone forgets to enter a +x to hit, or enter a damage value, we are throwing a console error.  Would be better to log this to chat so people know what they need to fix.

**Comment by mooped** [comment] 2020-11-11 21:44
Duplicate of #25

**Closed by mooped** 2020-11-11 21:44 UTC
Labels: enhancement, for v1.0
